apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-sbyn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-sbyn
    app.kubernetes.io/part-of: load-app-17a736c8-0501-449b-a36c-1d3901dd8112
  name: devfile-sample-sbyn
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-sbyn
status:
  loadBalancer: {}
